# -*- coding: utf-8 -*-
"""hw03-[2].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAjJwyEpNRBmTzZ6iwglo2CiaVjjATxD
"""

from mrjob.job import MRJob
import csv

class AvgWords(MRJob):

    def mapper(self, _, line):
        test = csv.reader([line])
        line_split = next(test)
        yield "num", len (line_split[1].split(' '))

    def reducer(self, key, values):
        yield key, sum(vals)
    


if __name__ == '__main__':
    AvgWords.run()