# -*- coding: utf-8 -*-
"""hw03-[3].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1833zV14wdkbn0SCn1e81UJs6CG5sEQps
"""

from mrjob.job import MRJob
import csv

class AvgWords(MRJob):

    def mapper(self, _, line):
        test = csv.reader([line])
        line_split = next(test)
        if cool: yield "num", test[3]

    def reducer(self, key, values):
        yield key, avg = sum(values)/ len(values)
        print(avg)
    


if __name__ == '__main__':
    AvgWords.run()