# -*- coding: utf-8 -*-
"""hw03-[1].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s2wbyl9Gbb1F-Oom8-I0tU95XtBAlE3J
"""

from mrjob.job import MRJob
import csv

class AvgWords(MRJob):

    def mapper(self, _, line):
        test = csv.reader([line])
        line_split = next(test)
        yield "num", len (line_split[4].split(' '))

    def reducer(self, key, values):
        yield key, avg = sum(values)/ len(values)
        print(avg)
    


if __name__ == '__main__':
    AvgWords.run()
